replicaCount: 1

env: prod

image:
  repository: asia-southeast2-docker.pkg.dev/amartha-ewallet-dev-370304/docker/go-accounting
  pullPolicy: IfNotPresent
  tag: ""

args:
  - ./go-accounting-consumer
  - run
  - "-n=account_relationships_migration"

serviceAccount:
  create: true
  annotations: {}
  name: "go-accounting-consumer-accountrelationshipmigration"

extraEnvs: []

readinessProbe:
  failureThreshold: 10
  httpGet:
    path: /api/health/readiness
    port: 80
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10

resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 200Mi

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "80"
  prometheus.io/path: "/metrics"

# autoscaling:
#   enabled: false
#   # minReplicas: 1
#   # maxReplicas: 2
#   # targetMemoryUtilizationPercentage: 80
#   # targetCPUUtilizationPercentage: 80

volumeMounts:
  - name: secret-volume
    mountPath: /opt/Amartha/config
    readOnly: true

volumes:
  - name: secret-volume
    secret:
      secretName: go-accounting-consumer-accountrelationshipmigration-vault-service

vault:
  enabled: true
  auth:
    method: "kubernetes"
    kubernetes:
      role: go-accounting-consumer-accountrelationshipmigration
      serviceAccount: go-accounting-consumer-accountrelationshipmigration
  secrets:
    service:
      secretPath: apps/core-finance-platform/GO_ACCOUNTING