replicaCount: 30

env: prod

image:
  repository: asia-southeast2-docker.pkg.dev/amartha-ewallet-dev-370304/docker/go-accounting
  pullPolicy: IfNotPresent
  tag: ""

args:
  - ./go-accounting-consumer
  - run
  - "-n=journal_stream"

serviceAccount:
  create: true
  annotations: {}
  name: "go-accounting-consumer-journalstream"

extraEnvs: []

readinessProbe:
  failureThreshold: 10
  httpGet:
    path: /api/health/readiness
    port: 80
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10

resources:
  limits:
    cpu: 600m
    memory: 200Mi
  requests:
    cpu: 300m
    memory: 100Mi

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "80"
  prometheus.io/path: "/metrics"

# autoscaling:
#   enabled: true
#   minReplicas: 10
#   maxReplicas: 30
#   targetCPUUtilizationPercentage: 80
#   targetMemoryUtilizationPercentage: 80

volumeMounts:
  - name: secret-volume
    mountPath: /opt/Amartha/config
    readOnly: true

volumes:
  - name: secret-volume
    secret:
      secretName: go-accounting-consumer-journalstream-vault-service

vault:
  enabled: true
  auth:
    method: "kubernetes"
    kubernetes:
      role: go-accounting-consumer-journalstream
      serviceAccount: go-accounting-consumer-journalstream
  secrets:
    service:
      secretPath: apps/core-finance-platform/GO_ACCOUNTING